.TH "src/renderer Directory Reference" 3 "Thu Jun 4 2015" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/renderer Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdeferred_renderer\&.c\fP"
.br
.ti -1c
.RI "file \fBforward_renderer\&.c\fP"
.br
.ti -1c
.RI "file \fBrenderer\&.c\fP"
.br
.in -1c
