.TH "src/object Directory Reference" 3 "Thu Jun 4 2015" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/object Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmtl_loader\&.c\fP"
.br
.ti -1c
.RI "file \fBobj_loader\&.c\fP"
.br
.ti -1c
.RI "file \fBobject\&.c\fP"
.br
.in -1c
