.TH "face_group" 3 "Thu Jun 4 2015" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
face_group \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int *** \fBfaces\fP"
.br
.ti -1c
.RI "int \fBface_count\fP"
.br
.ti -1c
.RI "int \fBallocated_face_count\fP"
.br
.ti -1c
.RI "\fBgfks_material\fP * \fBmat\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
