.TH "gfks_render_queue_item" 3 "Thu Jun 4 2015" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_render_queue_item \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgfks_mesh\fP * \fBmesh\fP"
.br
.ti -1c
.RI "\fBgfks_material\fP * \fBmaterial\fP"
.br
.ti -1c
.RI "\fBgfks_object\fP * \fBparent_object\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
