.TH "gfks_point_light" 3 "Thu Jun 4 2015" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_point_light \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.ti -1c
.RI "float \fBbrightness\fP"
.br
.ti -1c
.RI "int \fBattenuation_mode\fP"
.br
.ti -1c
.RI "float \fBattenuation_strength\fP"
.br
.ti -1c
.RI "float \fBcolor_r\fP"
.br
.ti -1c
.RI "float \fBcolor_g\fP"
.br
.ti -1c
.RI "float \fBcolor_b\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
