.TH "mat" 3 "Thu Jun 4 2015" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mat \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float * \fBdiffuse_color\fP"
.br
.ti -1c
.RI "float \fBspecularity_hardness\fP"
.br
.ti -1c
.RI "float \fBspecularity_color_r\fP"
.br
.ti -1c
.RI "float \fBspecularity_color_g\fP"
.br
.ti -1c
.RI "float \fBspecularity_color_b\fP"
.br
.ti -1c
.RI "gfks_renderer_flags \fBrenderer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
