#ifndef MATERIAL_DF_H
#define MATERIAL_DF_H
const GLint GRAFFIKS_MATERIAL_DF_ATTRIB_POSITION = 0;
const GLint GRAFFIKS_MATERIAL_DF_ATTRIB_NORMAL = 1;
const GLint GRAFFIKS_MATERIAL_DF_ATTRIB_DIFFUSE_COLOR = 2;
const GLint GRAFFIKS_MATERIAL_DF_UATTRIB_MVP_MATRIX = 3;
const GLint GRAFFIKS_MATERIAL_DF_UATTRIB_MV_MATRIX = 4;
const GLint GRAFFIKS_MATERIAL_DF_UATTRIB_AMBIENT_COLOR = 5;
const GLint GRAFFIKS_MATERIAL_DF_UATTRIB_DIFFUSE_COLOR = 6;
const GLint GRAFFIKS_MATERIAL_DF_UATTRIB_DIFFUSE_INTENSITY = 7;
const GLint GRAFFIKS_MATERIAL_DF_UATTRIB_PER_VERTEX = 8;
const GLint GRAFFIKS_MATERIAL_DF_UATTRIB_LIGHT_POSITION = 100;
#endif
