.TH "gfks_camera" 3 "Thu Dec 5 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_camera
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBlocation_x\fP"
.br
.ti -1c
.RI "float \fBlocation_y\fP"
.br
.ti -1c
.RI "float \fBlocation_z\fP"
.br
.ti -1c
.RI "float \fBtarget_x\fP"
.br
.ti -1c
.RI "float \fBtarget_y\fP"
.br
.ti -1c
.RI "float \fBtarget_z\fP"
.br
.ti -1c
.RI "float \fBup_x\fP"
.br
.ti -1c
.RI "float \fBup_y\fP"
.br
.ti -1c
.RI "float \fBup_z\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
