.TH "gfks_device_protected" 3 "Tue Dec 10 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_device_protected
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkPhysicalDevice \fBvk_physical_device\fP"
.br
.ti -1c
.RI "int \fBvk_physical_device_index\fP"
.br
.ti -1c
.RI "VkPhysicalDeviceProperties * \fBvk_physical_device_properties\fP"
.br
.ti -1c
.RI "VkPhysicalDeviceFeatures * \fBvk_physical_device_features\fP"
.br
.ti -1c
.RI "VkDevice \fBvk_logical_device\fP"
.br
.ti -1c
.RI "unsigned int \fBvk_queue_family_property_count\fP"
.br
.ti -1c
.RI "VkQueueFamilyProperties * \fBvk_queue_family_properties\fP"
.br
.ti -1c
.RI "unsigned int \fBqueue_count\fP"
.br
.ti -1c
.RI "VkQueue * \fBqueues\fP"
.br
.ti -1c
.RI "unsigned int * \fBqueue_families_for_queues\fP"
.br
.ti -1c
.RI "unsigned int \fBgraphics_queue_count\fP"
.br
.ti -1c
.RI "unsigned int * \fBgraphics_queue_indices\fP"
.br
.ti -1c
.RI "unsigned int \fBcompute_queue_count\fP"
.br
.ti -1c
.RI "unsigned int * \fBcompute_queue_indices\fP"
.br
.ti -1c
.RI "unsigned int \fBtransfer_queue_count\fP"
.br
.ti -1c
.RI "unsigned int * \fBtransfer_queue_indices\fP"
.br
.ti -1c
.RI "unsigned int \fBsparse_binding_queue_count\fP"
.br
.ti -1c
.RI "unsigned int * \fBsparse_binding_queue_indices\fP"
.br
.ti -1c
.RI "unsigned int \fBpresentation_queue_count\fP"
.br
.ti -1c
.RI "unsigned int * \fBpresentation_queue_indices\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned int gfks_device_protected::compute_queue_count"

.SS "unsigned int* gfks_device_protected::compute_queue_indices"

.SS "unsigned int gfks_device_protected::graphics_queue_count"

.SS "unsigned int* gfks_device_protected::graphics_queue_indices"

.SS "unsigned int gfks_device_protected::presentation_queue_count"

.SS "unsigned int* gfks_device_protected::presentation_queue_indices"

.SS "unsigned int gfks_device_protected::queue_count"

.SS "unsigned int* gfks_device_protected::queue_families_for_queues"

.SS "VkQueue* gfks_device_protected::queues"

.SS "unsigned int gfks_device_protected::sparse_binding_queue_count"

.SS "unsigned int* gfks_device_protected::sparse_binding_queue_indices"

.SS "unsigned int gfks_device_protected::transfer_queue_count"

.SS "unsigned int* gfks_device_protected::transfer_queue_indices"

.SS "VkDevice gfks_device_protected::vk_logical_device"

.SS "VkPhysicalDevice gfks_device_protected::vk_physical_device"

.SS "VkPhysicalDeviceFeatures* gfks_device_protected::vk_physical_device_features"

.SS "int gfks_device_protected::vk_physical_device_index"

.SS "VkPhysicalDeviceProperties* gfks_device_protected::vk_physical_device_properties"

.SS "VkQueueFamilyProperties* gfks_device_protected::vk_queue_family_properties"

.SS "unsigned int gfks_device_protected::vk_queue_family_property_count"


.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
