.TH "gfks_mesh" 3 "Thu Dec 5 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_mesh
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "GLuint \fBtriangle_buffer\fP"
.br
.ti -1c
.RI "GLuint \fBnormal_buffer\fP"
.br
.ti -1c
.RI "GLuint \fBvertex_color_buffer\fP"
.br
.ti -1c
.RI "int \fBvertex_count\fP"
.br
.ti -1c
.RI "int \fBnormal_count\fP"
.br
.ti -1c
.RI "float \fBlocation_x\fP"
.br
.ti -1c
.RI "float \fBlocation_y\fP"
.br
.ti -1c
.RI "float \fBlocation_z\fP"
.br
.ti -1c
.RI "float \fBangle\fP"
.br
.ti -1c
.RI "float \fBrot_x\fP"
.br
.ti -1c
.RI "float \fBrot_y\fP"
.br
.ti -1c
.RI "float \fBrot_z\fP"
.br
.ti -1c
.RI "bool \fBuse_vertex_color\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
