.TH "gfks_context_protected" 3 "Tue Dec 10 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_context_protected
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VkInstance * \fBvk_instance\fP"
.br
.ti -1c
.RI "int \fBenabled_vulkan_extension_count\fP"
.br
.ti -1c
.RI "const char ** \fBenabled_extensions\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char** gfks_context_protected::enabled_extensions"

.SS "int gfks_context_protected::enabled_vulkan_extension_count"

.SS "VkInstance* gfks_context_protected::vk_instance"


.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
