.TH "gfks_texture" 3 "Thu Dec 5 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_texture
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float ** \fBuv\fP"
.br
.ti -1c
.RI "GLuint \fBtex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
