.TH "gfks_object" 3 "Thu Dec 5 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_object
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgfks_mesh\fP ** \fBmeshes\fP"
.br
.ti -1c
.RI "\fBgfks_material\fP ** \fBmats\fP"
.br
.ti -1c
.RI "int \fBmesh_count\fP"
.br
.ti -1c
.RI "float \fBlocation_x\fP"
.br
.ti -1c
.RI "float \fBlocation_y\fP"
.br
.ti -1c
.RI "float \fBlocation_z\fP"
.br
.ti -1c
.RI "float \fBangle\fP"
.br
.ti -1c
.RI "float \fBrot_x\fP"
.br
.ti -1c
.RI "float \fBrot_y\fP"
.br
.ti -1c
.RI "float \fBrot_z\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
