.TH "gfks_surface_protected" 3 "Thu Dec 5 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_surface_protected
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "gfks_context * \fBcontext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "gfks_context* gfks_surface_protected::context"


.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
