.TH "gfks_surface" 3 "Tue Dec 10 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfks_surface \- gfks_surface  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graffiks\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "gfks_surface * \fBgfks_create_surface\fP ()"
.br
.RI "Creates a new Graffiks surface\&. "
.ti -1c
.RI "gfks_surface * \fBgfks_create_surface_X11\fP (gfks_context *\fBcontext\fP, Display *display, Window window)"
.br
.RI "Creates a new Graffiks surface for an X11 window\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "gfks_context * \fBcontext\fP"
.br
.RI "Read only\&. The parent Graffiks context\&. "
.ti -1c
.RI "gfks_device * \fBdraw_device\fP"
.br
.RI "Read only, use set_draw_device\&. The device we'll use when drawing to this surface\&. "
.ti -1c
.RI "bool(* \fBset_draw_device\fP )(gfks_surface *surface, gfks_device *device)"
.br
.RI "Sets which device will be used to draw to this surface\&. "
.ti -1c
.RI "void(* \fBfree\fP )(gfks_surface *surface)"
.br
.RI "Frees a surface\&. "
.in -1c
.SH "Detailed Description"
.PP 
gfks_surface 
.SH "Member Function Documentation"
.PP 
.SS "gfks_surface * gfks_create_surface ()"

.PP
Creates a new Graffiks surface\&. CURRENTLY UNIMPLEMENTED
.PP
\fBReturns\fP
.RS 4
A Graffiks context\&. NULL if there was an error\&. 
.RE
.PP

.SS "gfks_surface * gfks_create_surface_X11 (gfks_context * context, Display * display, Window window)"

.PP
Creates a new Graffiks surface for an X11 window\&. Only present when GFKS_CONFIG_X11_SUPPORT is defined at build time\&.
.PP
\fBParameters\fP
.RS 4
\fIdisplay\fP An X11 display 
.br
\fIwindow\fP An X11 window 
.RE
.PP
\fBReturns\fP
.RS 4
A Graffiks context\&. NULL if there was an error\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "void(* free) (gfks_surface *surface)"

.PP
Frees a surface\&. Must be called when you're done! 
.PP
\fBParameters\fP
.RS 4
\fIgfks_surface\fP A surface to be destroyed 
.RE
.PP

.SS "bool(* set_draw_device) (gfks_surface *surface, gfks_device *device)"

.PP
Sets which device will be used to draw to this surface\&. 
.PP
\fBParameters\fP
.RS 4
\fIgfks_surface\fP The surface we want this device to draw to 
.br
\fIgfks_device\fP The device we want to use to draw to this surface 
.RE
.PP
\fBReturns\fP
.RS 4
true on success, false on error - look at gfks_latest_error to get more information\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
