.TH "include/graffiks/model_loaders/obj_loader.h" 3 "Thu Dec 5 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/graffiks/model_loaders/obj_loader.h
.SH SYNOPSIS
.br
.PP
\fC#include 'graffiks/mesh\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'graffiks/object\&.h'\fP
.br
\fC#include 'graffiks/material\&.h'\fP
.br
\fC#include 'graffiks/renderer/renderer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgfks_object\fP * \fBgfks_load_obj\fP (gfks_renderer_flags flags, char *filepath)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
