.TH "include/graffiks/texture.h" 3 "Tue Dec 10 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/graffiks/texture.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBgfks_texture\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgfks_texture\fP * \fBgfks_create_texture\fP (float **uv, char *filepath)"
.br
.ti -1c
.RI "void \fBgfks_free_texture\fP (\fBgfks_texture\fP *t)"
.br
.in -1c
.SH "Class Documentation"
.PP 
.SH "struct gfks_texture"
.PP 
\fBClass Members:\fP
.RS 4
GLuint \fItex\fP 
.br
.PP
float ** \fIuv\fP 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
