.TH "window_system_extension_map" 3 "Thu Dec 5 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window_system_extension_map
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "gfks_window_system \fBwindow_system\fP"
.br
.ti -1c
.RI "char * \fBvulkan_extension\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* window_system_extension_map::vulkan_extension"

.SS "gfks_window_system window_system_extension_map::window_system"


.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
