.TH "window_handle_x11" 3 "Tue Dec 10 2019" "Graffiks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window_handle_x11
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "Window \fBwindow\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Display* window_handle_x11::display"

.SS "Window window_handle_x11::window"


.SH "Author"
.PP 
Generated automatically by Doxygen for Graffiks from the source code\&.
